name: Frontend-test

on: push 

jobs:
  super-lint:
    name: Lint code branche
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v
      - name: Run super linter 
        uses: github/super-lint@v3

# name: Frontend CI

# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main, develop ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Use Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm

#       - name: Install deps
#         run: npm ci

#       - name: Run tests
#         run: npm run test

#       - name: Build app
#         run: npm run build
